### ISSUE TITLE
jit.persephone doesn't always allow throughput

### ISSUE THREAD

**Issue by jacklion710** [tmhglnd/jit.underworld#11]
I recorded a clip [here](https://www.dropbox.com/s/ogevtv84a8rf3io/jit.persephone%20issue.mkv?dl=0) where you can see jit.persephone blocking a bang message from passing regardless of whether it is set to @capture 0 or 1. Sometimes reinstantiating it fixes the issue but in this case it is not so. I will try and work on recreating the issue but it happens so sporadically so i'm not exactly sure what causes it.

**Comment by tmhglnd** [comment]
Hey thanks for the report. The thing is, the object is only made to capture int, float and list, no bangs. The reson is that it is actually capturing a value for every frame and outputting that at the framerate render bang (you'll see when you attach an int and give it some number, it will output this number at framerate). This would mean for bangs that it would continously output bangs which is probably not what you want since I guess this should be a trigger at a specific time. Maybe I need to completely reconsider how this object works, and let it only output a value at a specific time in the composition. The reason i choose this approach is that you can always "scrub" through the captured data since you know the value at every frametime, leaving no gaps. I'm not sure what you want to do with the bang, but for example if the bang would trigger some random number to adjust some visual then you would actually want to capture that number, not the trigger. Hope this helps, but if you have a clear usecase I happy to look into it further
